---

apt:
  keyring: "/etc/apt/keyrings"
  sources: "/etc/apt/sources.list.d"
  trusted: "/etc/apt/trusted.gpg.d"

  default_packages:
    - git
    - vim
    - ca-certificates
    - curl
    - dpkg
    - sudo  # Required for 'become' to work.
    - jq
    - yq
    - python3-pip
    - mtr
    - net-tools

su_user: root
su_group: root
system_user: root
